CREATE TABLE "Person" (
"PersonID" INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
"Name" TEXT NOT NULL,
"Age" INTEGER NOT NULL
);

CREATE TABLE "Employee" (
"EmployeeID" INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
"HoursWorked" REAL NOT NULL
);

CREATE TABLE "Company" (
"PersonID" INTEGER NOT NULL,
"EmployeeID" INTEGER NOT NULL,
PRIMARY KEY("PersonID", "EmployeeID"),
FOREIGN KEY("PersonID") REFERENCES Person("PersonID"),
FOREIGN KEY("EmployeeID") REFERENCES Employee("EmployeeID")
)
